name: Issue Comment
on:
  pull_request:
    types:
      - opened

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hyeongyuan/review-gpt-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
